# Generated by Django 3.2.8 on 2021-12-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_sessioninfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninfo',
            old_name='mediaPaths',
            new_name='audio',
        ),
    ]
