# Generated by Django 3.2.8 on 2021-12-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_rename_mediapaths_sessioninfo_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
