# Generated by Django 3.2.8 on 2021-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_audiostorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiostorage',
            name='audio_file',
            field=models.FileField(upload_to='..\\uploads\\'),
        ),
    ]
