# Generated by Django 3.2.8 on 2021-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_audiostorage_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiostorage',
            name='audio_file',
            field=models.FileField(upload_to='.\\uploads\\'),
        ),
    ]
